// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0--rc1
// source: proto/KafkaService.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Response_WorkerStatus int32

const (
	Response_RUNNING        Response_WorkerStatus = 0
	Response_TERMINATED     Response_WorkerStatus = 1
	Response_NOT_FOUND      Response_WorkerStatus = 2
	Response_INTERNAL_ERROR Response_WorkerStatus = 3
)

// Enum value maps for Response_WorkerStatus.
var (
	Response_WorkerStatus_name = map[int32]string{
		0: "RUNNING",
		1: "TERMINATED",
		2: "NOT_FOUND",
		3: "INTERNAL_ERROR",
	}
	Response_WorkerStatus_value = map[string]int32{
		"RUNNING":        0,
		"TERMINATED":     1,
		"NOT_FOUND":      2,
		"INTERNAL_ERROR": 3,
	}
)

func (x Response_WorkerStatus) Enum() *Response_WorkerStatus {
	p := new(Response_WorkerStatus)
	*p = x
	return p
}

func (x Response_WorkerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Response_WorkerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_KafkaService_proto_enumTypes[0].Descriptor()
}

func (Response_WorkerStatus) Type() protoreflect.EnumType {
	return &file_proto_KafkaService_proto_enumTypes[0]
}

func (x Response_WorkerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Response_WorkerStatus.Descriptor instead.
func (Response_WorkerStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_KafkaService_proto_rawDescGZIP(), []int{2, 0}
}

type ConsumerRequestWithTransformation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InTopic      string `protobuf:"bytes,1,opt,name=inTopic,proto3" json:"inTopic,omitempty"`
	OutTopic     string `protobuf:"bytes,2,opt,name=outTopic,proto3" json:"outTopic,omitempty"`
	GroovyScript string `protobuf:"bytes,3,opt,name=groovyScript,proto3" json:"groovyScript,omitempty"`
	PipelineId   string `protobuf:"bytes,4,opt,name=pipelineId,proto3" json:"pipelineId,omitempty"`
}

func (x *ConsumerRequestWithTransformation) Reset() {
	*x = ConsumerRequestWithTransformation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_KafkaService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsumerRequestWithTransformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerRequestWithTransformation) ProtoMessage() {}

func (x *ConsumerRequestWithTransformation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_KafkaService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerRequestWithTransformation.ProtoReflect.Descriptor instead.
func (*ConsumerRequestWithTransformation) Descriptor() ([]byte, []int) {
	return file_proto_KafkaService_proto_rawDescGZIP(), []int{0}
}

func (x *ConsumerRequestWithTransformation) GetInTopic() string {
	if x != nil {
		return x.InTopic
	}
	return ""
}

func (x *ConsumerRequestWithTransformation) GetOutTopic() string {
	if x != nil {
		return x.OutTopic
	}
	return ""
}

func (x *ConsumerRequestWithTransformation) GetGroovyScript() string {
	if x != nil {
		return x.GroovyScript
	}
	return ""
}

func (x *ConsumerRequestWithTransformation) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

type ConsumerRequestWithHadoop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InTopic      string `protobuf:"bytes,1,opt,name=inTopic,proto3" json:"inTopic,omitempty"`
	HdfsFileName string `protobuf:"bytes,2,opt,name=hdfsFileName,proto3" json:"hdfsFileName,omitempty"`
	PipelineId   string `protobuf:"bytes,3,opt,name=pipelineId,proto3" json:"pipelineId,omitempty"`
}

func (x *ConsumerRequestWithHadoop) Reset() {
	*x = ConsumerRequestWithHadoop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_KafkaService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsumerRequestWithHadoop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerRequestWithHadoop) ProtoMessage() {}

func (x *ConsumerRequestWithHadoop) ProtoReflect() protoreflect.Message {
	mi := &file_proto_KafkaService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerRequestWithHadoop.ProtoReflect.Descriptor instead.
func (*ConsumerRequestWithHadoop) Descriptor() ([]byte, []int) {
	return file_proto_KafkaService_proto_rawDescGZIP(), []int{1}
}

func (x *ConsumerRequestWithHadoop) GetInTopic() string {
	if x != nil {
		return x.InTopic
	}
	return ""
}

func (x *ConsumerRequestWithHadoop) GetHdfsFileName() string {
	if x != nil {
		return x.HdfsFileName
	}
	return ""
}

func (x *ConsumerRequestWithHadoop) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   Response_WorkerStatus `protobuf:"varint,1,opt,name=status,proto3,enum=Response_WorkerStatus" json:"status,omitempty"`
	WorkerId string                `protobuf:"bytes,2,opt,name=workerId,proto3" json:"workerId,omitempty"`
	Message  string                `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_KafkaService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_KafkaService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_KafkaService_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetStatus() Response_WorkerStatus {
	if x != nil {
		return x.Status
	}
	return Response_RUNNING
}

func (x *Response) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerId string `protobuf:"bytes,1,opt,name=workerId,proto3" json:"workerId,omitempty"`
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_KafkaService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_KafkaService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_KafkaService_proto_rawDescGZIP(), []int{3}
}

func (x *PingRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

var File_proto_KafkaService_proto protoreflect.FileDescriptor

var file_proto_KafkaService_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x4b, 0x61, 0x66, 0x6b, 0x61, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9d, 0x01, 0x0a, 0x21, 0x43,
	0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x57, 0x69,
	0x74, 0x68, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x69, 0x6e, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x75,
	0x74, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x75,
	0x74, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x22, 0x0a, 0x0c, 0x67, 0x72, 0x6f, 0x6f, 0x76, 0x79,
	0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x67, 0x72,
	0x6f, 0x6f, 0x76, 0x79, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x69,
	0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x22, 0x79, 0x0a, 0x19, 0x43, 0x6f,
	0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x57, 0x69, 0x74,
	0x68, 0x48, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x54, 0x6f, 0x70,
	0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x6e, 0x54, 0x6f, 0x70, 0x69,
	0x63, 0x12, 0x22, 0x0a, 0x0c, 0x68, 0x64, 0x66, 0x73, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x68, 0x64, 0x66, 0x73, 0x46, 0x69, 0x6c,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e,
	0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x69, 0x70, 0x65, 0x6c,
	0x69, 0x6e, 0x65, 0x49, 0x64, 0x22, 0xc0, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x16, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x57, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x4e, 0x0a, 0x0c, 0x57, 0x6f, 0x72, 0x6b,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e, 0x4e,
	0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x45, 0x52, 0x4d, 0x49, 0x4e, 0x41,
	0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55,
	0x4e, 0x44, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c,
	0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03, 0x22, 0x29, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x49, 0x64, 0x32, 0x9e, 0x02, 0x0a, 0x10, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x55, 0x0a, 0x24, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x4b, 0x61, 0x66, 0x6b, 0x61, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x57, 0x69,
	0x74, 0x68, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x22, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x09, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x49, 0x0a, 0x20, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4b, 0x61, 0x66, 0x6b, 0x61, 0x43, 0x6f, 0x6e,
	0x73, 0x75, 0x6d, 0x65, 0x72, 0x57, 0x69, 0x74, 0x68, 0x48, 0x44, 0x46, 0x53, 0x50, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x12, 0x1a, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x48, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x1a,
	0x09, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x23, 0x53, 0x74,
	0x6f, 0x70, 0x4b, 0x61, 0x66, 0x6b, 0x61, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x57,
	0x69, 0x74, 0x68, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x0c, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x09, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x0d, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x12, 0x0c, 0x2e, 0x50, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x35, 0x0a, 0x1b, 0x69, 0x6f, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x68,
	0x69, 0x76, 0x65, 0x2e, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x42, 0x0c, 0x4b, 0x61, 0x66, 0x6b, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x50, 0x01, 0x5a, 0x06, 0x2e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_KafkaService_proto_rawDescOnce sync.Once
	file_proto_KafkaService_proto_rawDescData = file_proto_KafkaService_proto_rawDesc
)

func file_proto_KafkaService_proto_rawDescGZIP() []byte {
	file_proto_KafkaService_proto_rawDescOnce.Do(func() {
		file_proto_KafkaService_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_KafkaService_proto_rawDescData)
	})
	return file_proto_KafkaService_proto_rawDescData
}

var file_proto_KafkaService_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_KafkaService_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_KafkaService_proto_goTypes = []interface{}{
	(Response_WorkerStatus)(0),                // 0: Response.WorkerStatus
	(*ConsumerRequestWithTransformation)(nil), // 1: ConsumerRequestWithTransformation
	(*ConsumerRequestWithHadoop)(nil),         // 2: ConsumerRequestWithHadoop
	(*Response)(nil),                          // 3: Response
	(*PingRequest)(nil),                       // 4: PingRequest
}
var file_proto_KafkaService_proto_depIdxs = []int32{
	0, // 0: Response.status:type_name -> Response.WorkerStatus
	1, // 1: IngestionService.StartKafkaConsumerWithTransformation:input_type -> ConsumerRequestWithTransformation
	2, // 2: IngestionService.StartKafkaConsumerWithHDFSPlugin:input_type -> ConsumerRequestWithHadoop
	4, // 3: IngestionService.StopKafkaConsumerWithTransformation:input_type -> PingRequest
	4, // 4: IngestionService.CheckConsumer:input_type -> PingRequest
	3, // 5: IngestionService.StartKafkaConsumerWithTransformation:output_type -> Response
	3, // 6: IngestionService.StartKafkaConsumerWithHDFSPlugin:output_type -> Response
	3, // 7: IngestionService.StopKafkaConsumerWithTransformation:output_type -> Response
	3, // 8: IngestionService.CheckConsumer:output_type -> Response
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_KafkaService_proto_init() }
func file_proto_KafkaService_proto_init() {
	if File_proto_KafkaService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_KafkaService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsumerRequestWithTransformation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_KafkaService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsumerRequestWithHadoop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_KafkaService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_KafkaService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_KafkaService_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_KafkaService_proto_goTypes,
		DependencyIndexes: file_proto_KafkaService_proto_depIdxs,
		EnumInfos:         file_proto_KafkaService_proto_enumTypes,
		MessageInfos:      file_proto_KafkaService_proto_msgTypes,
	}.Build()
	File_proto_KafkaService_proto = out.File
	file_proto_KafkaService_proto_rawDesc = nil
	file_proto_KafkaService_proto_goTypes = nil
	file_proto_KafkaService_proto_depIdxs = nil
}
