// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0--rc1
// source: proto/SparkService.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobInfo_Status int32

const (
	JobInfo_RUNNING            JobInfo_Status = 0
	JobInfo_STOPPED            JobInfo_Status = 1
	JobInfo_TERMINATED         JobInfo_Status = 2
	JobInfo_NOT_FOUND          JobInfo_Status = 3
	JobInfo_SCHEDULING_FAILURE JobInfo_Status = 4
	JobInfo_RESOURCE_FAILURE   JobInfo_Status = 5
	JobInfo_INTERNAL_FAILRUE   JobInfo_Status = 6
)

// Enum value maps for JobInfo_Status.
var (
	JobInfo_Status_name = map[int32]string{
		0: "RUNNING",
		1: "STOPPED",
		2: "TERMINATED",
		3: "NOT_FOUND",
		4: "SCHEDULING_FAILURE",
		5: "RESOURCE_FAILURE",
		6: "INTERNAL_FAILRUE",
	}
	JobInfo_Status_value = map[string]int32{
		"RUNNING":            0,
		"STOPPED":            1,
		"TERMINATED":         2,
		"NOT_FOUND":          3,
		"SCHEDULING_FAILURE": 4,
		"RESOURCE_FAILURE":   5,
		"INTERNAL_FAILRUE":   6,
	}
)

func (x JobInfo_Status) Enum() *JobInfo_Status {
	p := new(JobInfo_Status)
	*p = x
	return p
}

func (x JobInfo_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobInfo_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_SparkService_proto_enumTypes[0].Descriptor()
}

func (JobInfo_Status) Type() protoreflect.EnumType {
	return &file_proto_SparkService_proto_enumTypes[0]
}

func (x JobInfo_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobInfo_Status.Descriptor instead.
func (JobInfo_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_SparkService_proto_rawDescGZIP(), []int{1, 0}
}

type SparkJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobName          string `protobuf:"bytes,1,opt,name=JobName,proto3" json:"JobName,omitempty"`
	DriverMemory     string `protobuf:"bytes,2,opt,name=DriverMemory,proto3" json:"DriverMemory,omitempty"`
	ExecutorMemory   string `protobuf:"bytes,3,opt,name=ExecutorMemory,proto3" json:"ExecutorMemory,omitempty"`
	ResourceLocation string `protobuf:"bytes,4,opt,name=ResourceLocation,proto3" json:"ResourceLocation,omitempty"`
	MainClass        string `protobuf:"bytes,5,opt,name=MainClass,proto3" json:"MainClass,omitempty"`
}

func (x *SparkJobRequest) Reset() {
	*x = SparkJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_SparkService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SparkJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SparkJobRequest) ProtoMessage() {}

func (x *SparkJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_SparkService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SparkJobRequest.ProtoReflect.Descriptor instead.
func (*SparkJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_SparkService_proto_rawDescGZIP(), []int{0}
}

func (x *SparkJobRequest) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *SparkJobRequest) GetDriverMemory() string {
	if x != nil {
		return x.DriverMemory
	}
	return ""
}

func (x *SparkJobRequest) GetExecutorMemory() string {
	if x != nil {
		return x.ExecutorMemory
	}
	return ""
}

func (x *SparkJobRequest) GetResourceLocation() string {
	if x != nil {
		return x.ResourceLocation
	}
	return ""
}

func (x *SparkJobRequest) GetMainClass() string {
	if x != nil {
		return x.MainClass
	}
	return ""
}

type JobInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerId  string         `protobuf:"bytes,1,opt,name=workerId,proto3" json:"workerId,omitempty"`
	JobStatus JobInfo_Status `protobuf:"varint,2,opt,name=jobStatus,proto3,enum=JobInfo_Status" json:"jobStatus,omitempty"`
	Message   string         `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *JobInfo) Reset() {
	*x = JobInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_SparkService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobInfo) ProtoMessage() {}

func (x *JobInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_SparkService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobInfo.ProtoReflect.Descriptor instead.
func (*JobInfo) Descriptor() ([]byte, []int) {
	return file_proto_SparkService_proto_rawDescGZIP(), []int{1}
}

func (x *JobInfo) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *JobInfo) GetJobStatus() JobInfo_Status {
	if x != nil {
		return x.JobStatus
	}
	return JobInfo_RUNNING
}

func (x *JobInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingJob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerId string `protobuf:"bytes,1,opt,name=workerId,proto3" json:"workerId,omitempty"`
}

func (x *PingJob) Reset() {
	*x = PingJob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_SparkService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingJob) ProtoMessage() {}

func (x *PingJob) ProtoReflect() protoreflect.Message {
	mi := &file_proto_SparkService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingJob.ProtoReflect.Descriptor instead.
func (*PingJob) Descriptor() ([]byte, []int) {
	return file_proto_SparkService_proto_rawDescGZIP(), []int{2}
}

func (x *PingJob) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

var File_proto_SparkService_proto protoreflect.FileDescriptor

var file_proto_SparkService_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x53, 0x70, 0x61, 0x72, 0x6b, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc1, 0x01, 0x0a, 0x0f, 0x53,
	0x70, 0x61, 0x72, 0x6b, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x4a, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x4a, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x44, 0x72, 0x69, 0x76,
	0x65, 0x72, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x26, 0x0a, 0x0e,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x4d, 0x65,
	0x6d, 0x6f, 0x72, 0x79, 0x12, 0x2a, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x61, 0x69, 0x6e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x4d, 0x61, 0x69, 0x6e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x22, 0xf6,
	0x01, 0x0a, 0x07, 0x4a, 0x6f, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x09, 0x6a, 0x6f, 0x62, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x4a, 0x6f, 0x62, 0x49,
	0x6e, 0x66, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x09, 0x6a, 0x6f, 0x62, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x85, 0x01, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55,
	0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x4f, 0x50, 0x50,
	0x45, 0x44, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x45, 0x52, 0x4d, 0x49, 0x4e, 0x41, 0x54,
	0x45, 0x44, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e,
	0x44, 0x10, 0x03, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x43, 0x48, 0x45, 0x44, 0x55, 0x4c, 0x49, 0x4e,
	0x47, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x55, 0x52, 0x45, 0x10, 0x04, 0x12, 0x14, 0x0a, 0x10, 0x52,
	0x45, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x55, 0x52, 0x45, 0x10,
	0x05, 0x12, 0x14, 0x0a, 0x10, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x46, 0x41,
	0x49, 0x4c, 0x52, 0x55, 0x45, 0x10, 0x06, 0x22, 0x25, 0x0a, 0x07, 0x50, 0x69, 0x6e, 0x67, 0x4a,
	0x6f, 0x62, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x32, 0x82,
	0x01, 0x0a, 0x0f, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x2b, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x70, 0x61, 0x72, 0x6b,
	0x4a, 0x6f, 0x62, 0x12, 0x10, 0x2e, 0x53, 0x70, 0x61, 0x72, 0x6b, 0x4a, 0x6f, 0x62, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x08, 0x2e, 0x4a, 0x6f, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x22, 0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x70, 0x61, 0x72, 0x6b, 0x4a, 0x6f, 0x62, 0x12,
	0x08, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x4a, 0x6f, 0x62, 0x1a, 0x08, 0x2e, 0x4a, 0x6f, 0x62, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x08, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4a, 0x6f, 0x62, 0x12,
	0x08, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x4a, 0x6f, 0x62, 0x1a, 0x08, 0x2e, 0x4a, 0x6f, 0x62, 0x49,
	0x6e, 0x66, 0x6f, 0x42, 0x31, 0x0a, 0x17, 0x69, 0x6f, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x68, 0x69,
	0x76, 0x65, 0x2e, 0x73, 0x70, 0x61, 0x72, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x0c,
	0x53, 0x70, 0x61, 0x72, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x01, 0x5a, 0x06,
	0x2e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_SparkService_proto_rawDescOnce sync.Once
	file_proto_SparkService_proto_rawDescData = file_proto_SparkService_proto_rawDesc
)

func file_proto_SparkService_proto_rawDescGZIP() []byte {
	file_proto_SparkService_proto_rawDescOnce.Do(func() {
		file_proto_SparkService_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_SparkService_proto_rawDescData)
	})
	return file_proto_SparkService_proto_rawDescData
}

var file_proto_SparkService_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_SparkService_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_SparkService_proto_goTypes = []interface{}{
	(JobInfo_Status)(0),     // 0: JobInfo.Status
	(*SparkJobRequest)(nil), // 1: SparkJobRequest
	(*JobInfo)(nil),         // 2: JobInfo
	(*PingJob)(nil),         // 3: PingJob
}
var file_proto_SparkService_proto_depIdxs = []int32{
	0, // 0: JobInfo.jobStatus:type_name -> JobInfo.Status
	1, // 1: AnalysisService.StartSparkJob:input_type -> SparkJobRequest
	3, // 2: AnalysisService.StopSparkJob:input_type -> PingJob
	3, // 3: AnalysisService.CheckJob:input_type -> PingJob
	2, // 4: AnalysisService.StartSparkJob:output_type -> JobInfo
	2, // 5: AnalysisService.StopSparkJob:output_type -> JobInfo
	2, // 6: AnalysisService.CheckJob:output_type -> JobInfo
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_SparkService_proto_init() }
func file_proto_SparkService_proto_init() {
	if File_proto_SparkService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_SparkService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SparkJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_SparkService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_SparkService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingJob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_SparkService_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_SparkService_proto_goTypes,
		DependencyIndexes: file_proto_SparkService_proto_depIdxs,
		EnumInfos:         file_proto_SparkService_proto_enumTypes,
		MessageInfos:      file_proto_SparkService_proto_msgTypes,
	}.Build()
	File_proto_SparkService_proto = out.File
	file_proto_SparkService_proto_rawDesc = nil
	file_proto_SparkService_proto_goTypes = nil
	file_proto_SparkService_proto_depIdxs = nil
}
